### ISSUE TITLE
Complete the code for Bresenham's Line generation algorithm

### ISSUE THREAD

**Issue by Persian-Prince** [Persian-Prince/OPEN-GL-Tutorials#1]
Edit the bresenham_line_generation.cpp file and complete the code.

**Comment by Joey-Tribyani** [comment]
Can you please assign this to me @Persian-Prince

**Comment by CodingWarrior33** [comment]
Hey could you assign this issue to me...

**Comment by Joeey-Tribyani** [comment]
please let me work on this

**Comment by CodingWarrior33** [comment]
Hey could you please assign this issue to me...

**Comment by Persian-Prince** [comment]
> please let me work on this

ok
