### ISSUE TITLE
Complete the code for Bresenham's Circle generation algorithm

### ISSUE THREAD

**Issue by Persian-Prince** [Persian-Prince/OPEN-GL-Tutorials#2]
Edit the bresenhams_circle.cpp file and complete the code.

**Comment by Joey-Tribyani** [comment]
Can you please assign this to me @Persian-Prince

**Comment by mihir02badkur** [comment]
Can you please assign this to me @Persian-Prince

**Comment by Joeey-Tribyani** [comment]
please let me work on this

**Comment by Joeey-Tribyani** [comment]
> Can you please assign this to me @Persian-Prince

complete your previously assigned issues please

**Comment by Joeey-Tribyani** [comment]
> please let me work on this

ok

**Comment by Persian-Prince** [comment]
> Can you please assign this to me @Persian-Prince
complete your previously assigned issues please

**Comment by Joeey-Tribyani** [comment]
> please let me work on this

ok

**Comment by Persian-Prince** [comment]
> please let me work on this

go ahead
