### ISSUE TITLE
Complete the code for Bezier curve drawing algorithm

### ISSUE THREAD

**Issue by Persian-Prince** [Persian-Prince/OPEN-GL-Tutorials#25]
Edit the bezier.cpp file and complete the code.

**Comment by S-kus** [comment]
Hey @Persian-Prince 
I would like to work on this issue, could you please assign it to me?

**Comment by Persian-Prince** [comment]
> Hey @Persian-Prince I would like to work on this issue, could you please assign it to me?

ok
