### ISSUE TITLE
Complete the code for Dashed Line generation algorithm

### ISSUE THREAD

**Issue by Persian-Prince** [Persian-Prince/OPEN-GL-Tutorials#3]
Edit the dashed_line.cpp file and complete the code.

**Comment by Joey-Tribyani** [comment]
Can you please assign this to me @Persian-Prince

**Comment by DivyeshAgarwaliitg21** [comment]
hey @Persian-Prince can you please assign me this

**Comment by Joeey-Tribyani** [comment]
> hey @Persian-Prince can you please assign me this

ok

**Comment by Persian-Prince** [comment]
> hey @Persian-Prince can you please assign me this

ok
