### ISSUE TITLE
Complete the code for Digital Differential Analyser Line generation algorithm

### ISSUE THREAD

**Issue by Persian-Prince** [Persian-Prince/OPEN-GL-Tutorials#4]
Edit the digital_differential_analyser.cpp file and complete the code.

**Comment by mihir02badkur** [comment]
Can you please assign this to me @Persian-Prince

**Comment by Persian-Prince** [comment]
> Can you please assign this to me @Persian-Prince

please complete #5 first

**Comment by Joeey-Tribyani** [comment]
i would like to work on this

**Comment by Joeey-Tribyani** [comment]
> i would like to work on this

ok

**Comment by Persian-Prince** [comment]
> i would like to work on this

ok
