### ISSUE TITLE
Complete the code for Bresenham's Ellipse generation algorithm

### ISSUE THREAD

**Issue by Persian-Prince** [Persian-Prince/OPEN-GL-Tutorials#5]
Edit the ellipse_bresenhams.cpp file and complete the code.

**Comment by Joey-Tribyani** [comment]
Can you please assign this to me @Persian-Prince

**Comment by mihir02badkur** [comment]
Can you please assign this to me @Persian-Prince

**Comment by Persian-Prince** [comment]
ok

**Comment by Manan-Rathi** [comment]
Hi @Persian-Prince. Could you please assign me to this issue?
