### ISSUE TITLE
Complete the code for Ellipse generation algorithm

### ISSUE THREAD

**Issue by Persian-Prince** [Persian-Prince/OPEN-GL-Tutorials#6]
Edit the ellipse_midpoint_algo.cpp file and complete the code.

**Comment by siddhesh-coder** [comment]
hello, can you please assign me this issue.

**Comment by Persian-Prince** [comment]
> hello, can you please assign me this issue.

You have already been assigned an issue #7 first please complete that.

**Comment by Joey-Tribyani** [comment]
Can you please assign this to me @Persian-Prince

**Comment by Joeey-Tribyani** [comment]
please assign this to me

**Comment by Persian-Prince** [comment]
> please assign this to me

ok
